# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMD.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(208, 210)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background:transparent;")
        self.centralwidget.setObjectName("centralwidget")
        self.triangle3 = QtWidgets.QLabel(self.centralwidget)
        self.triangle3.setGeometry(QtCore.QRect(43, 157, 121, 16))
        self.triangle3.setStyleSheet("background:transparent;")
        self.triangle3.setText("")
        self.triangle3.setPixmap(
            QtGui.QPixmap("files/triangle3.png"))
        self.triangle3.setScaledContents(True)
        self.triangle3.setObjectName("triangle3")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(5, 5, 200, 200))
        self.background.setAcceptDrops(False)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("background:transparent;")
        self.background.setText("")
        self.background.setPixmap(
            QtGui.QPixmap("files/circular.png"))
        self.background.setScaledContents(True)
        self.background.setAlignment(QtCore.Qt.AlignCenter)
        self.background.setObjectName("background")
        self.triangle1 = QtWidgets.QLabel(self.centralwidget)
        self.triangle1.setGeometry(QtCore.QRect(45, 25, 72, 120))
        self.triangle1.setAutoFillBackground(False)
        self.triangle1.setStyleSheet("background:transparent;")
        self.triangle1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.triangle1.setText("")
        self.triangle1.setPixmap(
            QtGui.QPixmap("files/triangle1.png"))
        self.triangle1.setScaledContents(True)
        self.triangle1.setWordWrap(False)
        self.triangle1.setOpenExternalLinks(False)
        self.triangle1.setObjectName("triangle1")
        self.triangle2 = QtWidgets.QLabel(self.centralwidget)
        self.triangle2.setGeometry(QtCore.QRect(110, 40, 45, 104))
        self.triangle2.setStyleSheet("background:transparent;")
        self.triangle2.setText("")
        self.triangle2.setPixmap(
            QtGui.QPixmap("files/triangle2.png"))
        self.triangle2.setScaledContents(True)
        self.triangle2.setObjectName("triangle2")
        self.background.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
